name: Environment Demo

on:
  push:
    branches: [ main ]

jobs:

  deploy-dev:
    runs-on: ubuntu-latest
    environment: devserver

    steps:
      - name: Show DEV server
        run: |
          echo "Server: $SERVER"
          echo "Password is hidden"

        env:
          SERVER: ${{ secrets.SERVER_NAME }}
          PASSWORD: ${{ secrets.SERVER_PASSWORD }}

  deploy-qa:
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: Show QA server
        run: |
          echo "Server: $SERVER"
          echo "Password is hidden"

        env:
          SERVER: ${{ secrets.SERVER_NAME }}
          PASSWORD: ${{ secrets.SERVER_PASSWORD }}

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Show PROD server
        run: |
          echo "Server: $SERVER"
          echo "Password is hidden"

        env:
          SERVER: ${{ secrets.SERVER_NAME }}
          PASSWORD: ${{ secrets.SERVER_PASSWORD }}